defaults:
  - dataset: MNIST
  - model: VAE
  - device: laptop

train_loader:
  _target_:  torch.utils.data.DataLoader
  dataset: ${dataset}
  shuffle: True
  batch_size: ${params.batch_size}
  num_workers: ${device.num_workers}

trainer:
  _target_: pytorch_lightning.Trainer
  logger:
    _target_: pytorch_lightning.loggers.WandbLogger
  callbacks:
    - _target_: callbacks.SamplingCallback
    - _target_: callbacks.ReconstructionCallback
  gpus: ${device.gpus}